version: '3.8'

services:

  node-server:
    build: ./node-server
    container_name: node-server

  python-server:
    build: ./python-server
    container_name: python-server

  springboot-server:
    build: ./springboot-server
    container_name: springboot-server

  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-server
      - python-server
      - springboot-server